services:
  seleniumbot:
    image: ghcr.io/lgiesken/seleniumbot:latest
    container_name: seleniumbot
    env_file:
      - .env
    command: >
      --username ${USERNAME}
      --password ${PASSWORD}
      --entryIds ${ENTRY_IDS}
      --minWait ${MIN_WAIT}
      --maxWait ${MAX_WAIT}
    depends_on:
      - selenium-hub

  selenium-hub:
    image: selenium/hub:4.23.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.23.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
