name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # optional: manuelles Starten

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      # 1. Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Login to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build Docker Image
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/seleniumbot:latest \
            -f SeleniumBot/Dockerfile .

      # 4. Push Docker Image
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/seleniumbot:latest
