name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      # 1. Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Login to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build and Push Docker Image
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/lgiesken/seleniumbot
          COMMIT_SHA=${GITHUB_SHA::7}

          # Build & push with "latest" and commit-specific tag
          docker buildx build \
            --push \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$COMMIT_SHA \
            -f Dockerfile .
